In [1]:
import pandas as pd
df = pd.read_csv("https://raw.githubusercontent.com/Datamanim/pandas/main/AB_NYC_2019.csv")

In [7]:
#[49] nieghbourhood_group 값에 따른 price값의 평균, 분산, 최대, 최소 값을 구하여라
df[['neighbourhood_group', 'price']]\
    .groupby('neighbourhood_group')\
    .agg(['mean', 'var', 'max', 'min'])

# 대괄호 두개를 통해서 'neighbourhood_group'과 'price'를 뽑아냄
# .groupby를 이용해서 그룹핑
# .agg는 집계 함수

                          price
                           mean           var    max min
neighbourhood_group
Bronx                 87.496792  11386.885081   2500   0
Brooklyn             124.383207  34921.719135  10000   0
Manhattan            196.875814  84904.159185  10000   0
Queens                99.517649  27923.130227  10000  10
Staten Island        114.812332  77073.088342   5000  13

In [10]:
#[50] neighbourhood_group 값에 따른 reviews_per_month 평균, 분산, 최대, 최소 값을 구하여라

df[['neighbourhood_group', 'reviews_per_month']].groupby('neighbourhood_group').agg(['mean', 'var', 'max', 'min'])

                    reviews_per_month
                                 mean       var    max   min
neighbourhood_group
Bronx                        1.837831  2.799878  10.34  0.02
Brooklyn                     1.283212  2.299040  14.00  0.01
Manhattan                    1.272131  2.651206  58.50  0.01
Queens                       1.941200  4.897848  20.94  0.01
Staten Island                1.872580  2.840895  10.12  0.02

In [ ]:
#[51] neighbourhood 값과 neighbourhood_group 값에 따른 price의 평균을 구하라
df.groupby(['neighbourhood', 'neighbourhood_group']).price.mean()   # "neighbourhood 값과 neighbourhood_group 값에 따른" --> 그룹핑
                                                                    # 한 컬럼에 대한 평균을 구하므로 .mean()을 이용

neighbourhood    neighbourhood_group
Allerton         Bronx                   87.595238
Arden Heights    Staten Island           67.250000
Arrochar         Staten Island          115.000000
Arverne          Queens                 171.779221
Astoria          Queens                 117.187778
                                           ...
Windsor Terrace  Brooklyn               138.993631
Woodhaven        Queens                  67.170455
Woodlawn         Bronx                   60.090909
Woodrow          Staten Island          700.000000
Woodside         Queens                  85.097872
Name: price, Length: 221, dtype: float64

In [ ]:
#[52] neighbourhood 값과 neighbourhood_group 값에 따른 price의 평균을 계층적으로 indexing 없이 구하라
df.groupby(['neighbourhood', 'neighbourhood_group']).price.mean().unstack()  # .unstack() --> 인덱스(행) 중 하나를 컬럼(열)로 만드는 것

neighbourhood_group,Bronx,Brooklyn,Manhattan,Queens,Staten Island
neighbourhood,,,,,
Allerton,87.595238,NaN,NaN,NaN,NaN
Arden Heights,NaN,NaN,NaN,NaN,67.25
Arrochar,NaN,NaN,NaN,NaN,115.00
Arverne,NaN,NaN,NaN,171.779221,NaN
Astoria,NaN,NaN,NaN,117.187778,NaN
...,...,...,...,...,...
Windsor Terrace,NaN,138.993631,NaN,NaN,NaN
Woodhaven,NaN,NaN,NaN,67.170455,NaN
Woodlawn,60.090909,NaN,NaN,NaN,NaN
Woodrow,NaN,NaN,NaN,NaN,700.00
Woodside,NaN,NaN,NaN,85.097872,NaN