In [1]:
import pandas as pd
df = pd.read_csv("https://raw.githubusercontent.com/Datamanim/pandas/main/AB_NYC_2019.csv")

In [2]:
#[45] 데이터의 각 host_name의 빈도수를 구하고 host_name으로 정렬하여 상위 5개를 출력하라
Ans = df.host_name.value_counts().sort_index()
Ans.head()

host_name
'Cil                        1
(Ari) HENRY LEE             1
(Email hidden by Airbnb)    6
(Mary) Haiy                 1
-TheQueensCornerLot         1
Name: count, dtype: int64

In [3]:
#[46] 데이터의 각 host_name의 빈도수를 구하고 빈도수 기준 내림차순 정렬한 데이터 프레임을 만들어라. 빈도수 컬럼은 counts로 명명하라
df.groupby('host_name').size().\
           to_frame().rename(columns={0:'counts'}).\
           sort_values('counts',ascending=False)

              counts
host_name
Michael          417
David            403
Sonder (NYC)     327
John             294
Alex             279
...              ...
诗月                 1
辣辣                 1
思铨                 1
文清                 1
文立                 1

[11452 rows x 1 columns]

In [7]:
#[47] neighbourhood_group의 값에 따른 neighbourhood 컬럼 값의 갯수를 구하여라
Ans = df.groupby(['neighbourhood_group', 'neighbourhood'], as_index=False).size()
Ans.head()

  neighbourhood_group neighbourhood  size
0               Bronx      Allerton    42
1               Bronx    Baychester     7
2               Bronx       Belmont    24
3               Bronx     Bronxdale    19
4               Bronx   Castle Hill     9

In [10]:
#[48] neighbourhood_group의 값에 따른 neighbourhood 컬럼 값 중 neighbourhood_group 그룹의 최댓값들을 출력하라
df.groupby(['neighbourhood_group', 'neighbourhood'], as_index=False).size()\
            .groupby(['neighbourhood_group'], as_index=False).max()

  neighbourhood_group    neighbourhood  size
0               Bronx         Woodlawn    70
1            Brooklyn  Windsor Terrace  3920
2           Manhattan     West Village  2658
3              Queens         Woodside   900
4       Staten Island          Woodrow    48