In [14]:
import pandas as pd
df = pd.read_csv("https://raw.githubusercontent.com/Datamanim/pandas/main/AB_NYC_2019.csv")

In [26]:
#[53] neighbourhood 값과 neighbourhood_group 값에 따른 price의 평균을 계층적 indexing 없이 구하고 nan 값은 -999값으로 채워라
Ans = df.groupby(['neighbourhood','neighbourhood_group'])\
    .price.mean()\
    .unstack()\
    .fillna(-999)
Ans.head()
# 그룹핑을 진행
# 값의 평균을 구함
# 열을 늘어진 데이터를 행으로 펼치기
# 빈칸을 원하는 숫자로 채우기

neighbourhood_group,Bronx,Brooklyn,Manhattan,Queens,Staten Island
neighbourhood,,,,,
Allerton,87.595238,-999.0,-999.0,-999.000000,-999.00
Arden Heights,-999.000000,-999.0,-999.0,-999.000000,67.25
Arrochar,-999.000000,-999.0,-999.0,-999.000000,115.00
Arverne,-999.000000,-999.0,-999.0,171.779221,-999.00
Astoria,-999.000000,-999.0,-999.0,117.187778,-999.00

In [17]:
#[54] 데이터 중 neighbourhood_group 값이 Queens값을 가지는 데이터들 중 neighbourhood 그룹별로 price값의 평균, 분산, 최대, 최소값을 구하라
Ans = df[df.neighbourhood_group == 'Queens']\
        .groupby(['neighbourhood'])\
        .price.agg(['mean', 'var', 'max', 'min'])
Ans.head()
# Queens 값을 갖는 neighbourhood_group을 분류
# neighbourhood로 그룹핑
# agg를 이용해서 price를 분류

                     mean            var    max  min
neighbourhood
Arverne        171.779221   37383.411141   1500   35
Astoria        117.187778  122428.811196  10000   25
Bay Terrace    142.000000    6816.400000    258   32
Bayside        157.948718  166106.470985   2600   30
Bayswater       87.470588    2330.889706    230   45

In [ ]:
#[55] 데이터 중 neighbourhood_group값에 따른 room_type 컬럼의 숫자를 구하고 neighbourhood_group값을 기준으로 각 값의 비율을 구하여라
df.groupby('neighbourhood_group')['room_type']\
    .value_counts(normalize=True).unstack()

# 그룹핑을 하고 ['room_type']의 정보만 꺼내옴
# normalize로 비율을 가져옴

room_type            Entire home/apt  Private room  Shared room
neighbourhood_group
Bronx                       0.347388      0.597617     0.054995
Brooklyn                    0.475478      0.503979     0.020543
Manhattan                   0.609344      0.368496     0.022160
Queens                      0.369926      0.595129     0.034945
Staten Island               0.471850      0.504021     0.024129

In [ ]:
#[56] 데이터를 로드하고 데이터 행과 열의 갯수를 출력하라
df = pd.read_csv("https://raw.githubusercontent.com/Datamanim/pandas/main/BankChurnersUp.csv")

df.shape

(10127, 19)